name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - feacture/**
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          DIR=$(find . -type d \( -name "dev" \))
          cd "$DIR"
          terraform init

      - name: Terraform Format Check
        run: |
          DIR=$(find . -type d \( -name "dev" \))
          cd "$DIR"
          terraform fmt -check

      - name: Terraform Validate
        run: |
          DIR=$(find . -type d \( -name "dev" \))
          cd "$DIR"
          terraform validate

      - name: Terraform Plan
        run: |
          DIR=$(find . -type d \( -name "dev" \))
          cd "$DIR"
          terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          DIR=$(find . -type d \( -name "dev" \))
          cd "$DIR"
          terraform apply -auto-approve